### ISSUE TITLE
The names already in circulation.

### ISSUE THREAD

**Issue by archae0pteryx** [niklasf/stockfish.pexe#2]
Hey-o. Heads up. Your repo matches the popular chess analytics engine "stockfish" this may or may not be of concern for you. Either way. Hi.

**Comment by niklasf** [comment]
Is this an auto generated message?

**Comment by archae0pteryx** [comment]
nope. just an avid chess player!

**Comment by niklasf** [comment]
Ok :) Check the README. This is a slightly modified version of the Stockfish chess engine that can run in your browser. You can see it in action on https://lichess.org/analysis.
