### ISSUE TITLE
Crash around depth 68 using "Go deeper!"

### ISSUE THREAD

**Issue by niklasf** [niklasf/stockfish.pexe#5]
https://de.lichess.org/analysis/standard/R7/P5k1/7p/8/8/6PP/r7/4K3_w_-_-_0_1#0

**Comment by isaacl** [comment]
I've managed to get a pnacl gdb session going with a debug build.

I'm hitting a segfault in the depth 40s in Position::is_draw. Crash occurs even with wilds disabled.  Will keep digging.

**Comment by ddugovic** [comment]
From a Linux shell I'm trying and have not yet encountered a crash, although around depth 50 `hashfull=999` occurs:

```
position fen R7/P5k1/7p/8/8/6PP/r7/4K3 w - - 0 1
go depth 100
```

**Comment by isaacl** [comment]
my initialization (probably doesn't matter)
```
setoption name Threads value 5
setoption name Hash value 512
setoption name MultiPV value 3
position fen R7/P5k1/7p/8/8/6PP/r7/4K3 w - - 0 1 moves
go depth 99
```

**Comment by niklasf** [comment]
Another RP endgame: https://en.lichess.org/analysis/standard/_6k1/p5pp/4p3/4Pp2/Ppr2P1P/1P4P1/2p2K2/2R5_b_-_-_0_37 crashes between 23 and 34

**Comment by ornicar** [comment]
best crashing position for me so far is `8/8/1p3pk1/2b2RPp/4Pq1K/2Q3PP/p7/8 w - - 2 42`

I had good crashes with Threads=7, Hash=16, around depth 22

**Comment by niklasf** [comment]
A pnacl build from official-stockfish/master (see master branch) is not crashing for me.

**Comment by arex1337** [comment]
8/2k5/1p2p3/3p1q1P/3n1N2/pP4Q1/P2K4/8 w - - 0 44
crashes on depth 24 in Chrome 56.0.2924.87

3/5 lines, 4/7 CPUs, 128MB memory

**Comment by arex1337** [comment]
8/4k3/8/6P1/6K1/8/7r/5R2 w - - 0 1 crashed at depth 35 in Chrome 56.0.2924.87

3/5 lines, 5/7 CPUs, 512MB memory

**Comment by niklasf** [comment]
Workaround deployed today: e881871921d1e6ad16e1cc7bb40308e2fe5b0ee0, 17d0842954b2419f40fe886b17dafbb9b8123727. We're not really sure why this seems to fix the issue.

**Comment by niklasf** [comment]
Fixed without performance regression by ddugovic/Stockfish#261.
