### ISSUE TITLE
Native Client Installation Fail

### ISSUE THREAD

**Issue by NotNate** [niklasf/stockfish.pexe#8]
Have been able to use the Stockfish on separate computers, but on my laptop, I always get the error:
third_party.fancy_urllib.InvalidCertificateException: Host storage.googleapis.com returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

This has come up whether I run naclsdk list or naclsdk update or really any naclsdk command. Without the nacl installation, I cannot use stockfish on my laptop, so help would be appreciated.

**Comment by niklasf** [comment]
Yes, it seems that naclsdk is just broken since recently. Fixing `UrlOpen` in `sdk_tools/download.py` helps temporarily: https://github.com/niklasf/stockfish.pexe/blob/97e7455d944d7b589987251d4d05077fd211553f/urlopen.patch#L6-L16

**Comment by NotNate** [comment]
@niklasf That seemed to fix it. Thanks.
